[build]
builder = "nixpacks"

[deploy]
startCommand = "node_modules/.bin/next start -p $PORT"
healthcheckPath = "/landing"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
